# Generated by Django 2.2.5 on 2021-01-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(db_column='LOCATION', default='İstanbul', max_length=100),
        ),
    ]
