# Generated by Django 2.2.5 on 2021-01-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisements',
        ),
    ]
