# Generated by Django 2.2.5 on 2021-01-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_advertisements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesatisfaction',
            name='customer_performance',
            field=models.IntegerField(db_column='CUSTOMERSCORE', null=True),
        ),
        migrations.AlterField(
            model_name='servicesatisfaction',
            name='provider_performance',
            field=models.IntegerField(db_column='PROVIDERSCORE', null=True),
        ),
    ]
