# Generated by Django 2.2.5 on 2021-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_serviceoffer_satisfaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_id',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(db_column='SERVICENAME', max_length=20, primary_key=True, serialize=False),
        ),
    ]
