# Generated by Django 2.2.5 on 2021-01-21 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210122_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionfails',
            name='satisfaction_id',
            field=models.ForeignKey(db_column='SATISFACID', max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.ServiceSatisfaction'),
        ),
    ]
