# Generated by Django 2.2.5 on 2021-01-21 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210122_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='context',
            field=models.CharField(db_column='CONTEXT', max_length=100),
        ),
        migrations.AlterField(
            model_name='offersessions',
            name='session_id',
            field=models.ForeignKey(db_column='SESSID', on_delete=django.db.models.deletion.CASCADE, to='home.Schedule'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='customer_conditions',
            field=models.CharField(db_column='CUSTOMERCOND', max_length=1000),
        ),
    ]
