# Generated by Django 2.2.5 on 2021-01-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210124_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashpass',
            field=models.BinaryField(db_column='HASHPASS', default=b''),
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.BinaryField(db_column='KEY', default=b''),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(db_column='MAIL', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(db_column='SURNAME', max_length=30),
        ),
    ]
